# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               arenzana.org
tagline:             The Simple
url:                 http://iarenzana.githug.io
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ismael Arenzana
  url:               https://twitter.com/iarenzana
  email:             iarenzana@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/iarenzana/iarenzana.github.io
