name: arenzana.org
description: Dev, IT, Photographer
meta_description: "iarenzana, Dev, IT, Photographer"

aboutPage: true

markdown: redcarpet
highlighter: pygments

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/5133407?v=3&amp;s=400

paginate: 20
baseurl: /
domain_name: 'arenzana.org'
google_analytics: 'UA-578689-9'
disqus: true
disqus_shortname: 'iarenzanagithubio'
comments: true

# Details for the RSS feed generator
url:            'arenzana.org'
author:         'Ismael Arenzana'
authorTwitter:  'iarenzana'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
